#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
#  hardware-compat — installer
#
#  Run once:   ./install.sh
#  After that: hardware-compat        (uses saved default mode)
#              hardware-compat --gui  (force GUI)
#              hardware-compat --cli  (force CLI)
# ══════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────
G="\033[0;32m"; Y="\033[0;33m"; R="\033[0;31m"; B="\033[1m"; NC="\033[0m"
ok()   { echo -e "  ${G}✓${NC}  $*"; }
warn() { echo -e "  ${Y}⚠${NC}  $*"; }
err()  { echo -e "  ${R}✗${NC}  $*"; }
step() { echo -e "\n  ${B}$*${NC}"; }

# ── Resolve project dir (where this script lives) ─────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_BIN="/usr/local/bin/hardware-compat"
DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/hardware-compat.desktop"
CONFIG_DIR="$HOME/.config/hardware-compat"

echo ""
echo -e "  ${B}hardware-compat installer${NC}"
echo    "  ──────────────────────────────────────────"

# ── Python check ──────────────────────────────────────────────────
step "Checking Python 3..."
if ! command -v python3 &>/dev/null; then
    err "python3 not found. Please install it first:"
    echo "     sudo apt install python3"
    exit 1
fi
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
if [[ $PY_MAJOR -lt 3 || ($PY_MAJOR -eq 3 && $PY_MINOR -lt 8) ]]; then
    err "Python 3.8+ required (found $PY_VER)"
    exit 1
fi
ok "Python $PY_VER"

# ── System tool check ─────────────────────────────────────────────
step "Checking system tools..."
MISSING_TOOLS=()
TOOL_PKGS=(
    "lspci:pciutils"
    "lsusb:usbutils"
    "rfkill:rfkill"
    "sensors:lm-sensors"
    "smartctl:smartmontools"
    "fwupdmgr:fwupd"
    "dmidecode:dmidecode"
)
for entry in "${TOOL_PKGS[@]}"; do
    tool="${entry%%:*}"
    pkg="${entry##*:}"
    if command -v "$tool" &>/dev/null; then
        ok "$tool"
    else
        warn "$tool not found  →  sudo apt install $pkg"
        MISSING_TOOLS+=("$pkg")
    fi
done

if [[ ${#MISSING_TOOLS[@]} -gt 0 ]]; then
    echo ""
    echo -e "  Install missing tools for best detection:"
    echo -e "  ${B}  sudo apt install -y ${MISSING_TOOLS[*]}${NC}"
    echo ""
    read -rp "  Install them now? [Y/n]: " ans
    ans="${ans:-Y}"
    if [[ "$ans" =~ ^[Yy]$ ]]; then
        sudo apt install -y "${MISSING_TOOLS[@]}" && ok "Tools installed"
    else
        warn "Skipped. Some features may be limited."
    fi
fi

# ── Create ~/.config/hardware-compat ─────────────────────────────
step "Creating config directory..."
mkdir -p "$CONFIG_DIR"
ok "$CONFIG_DIR"

# ── Write the launcher stub to /usr/local/bin ─────────────────────
step "Installing launcher to $INSTALL_BIN..."
sudo tee "$INSTALL_BIN" > /dev/null << STUB
#!/usr/bin/env bash
# hardware-compat launcher — auto-generated by install.sh
# Project lives at: ${SCRIPT_DIR}

PROJ="${SCRIPT_DIR}"
CFG="\$HOME/.config/hardware-compat/settings.json"

# ── Read default_mode from config if not overridden by flag ───────
get_default_mode() {
    if [[ -f "\$CFG" ]]; then
        python3 -c "
import json, sys
try:
    d = json.load(open('\$CFG'))
    print(d.get('default_mode', 'gui'))
except Exception:
    print('gui')
" 2>/dev/null || echo "gui"
    else
        echo "gui"
    fi
}

MODE="\$(get_default_mode)"

# ── Parse flags ───────────────────────────────────────────────────
PASSTHROUGH=()
for arg in "\$@"; do
    case "\$arg" in
        --gui)  MODE="gui"  ;;
        --cli)  MODE="cli"  ;;
        *)      PASSTHROUGH+=("\$arg") ;;
    esac
done

# ── Launch ────────────────────────────────────────────────────────
cd "\$PROJ"
if [[ "\$MODE" == "gui" ]]; then
    exec python3 gui_server.py "\${PASSTHROUGH[@]}"
else
    exec python3 main.py "\${PASSTHROUGH[@]}"
fi
STUB

sudo chmod +x "$INSTALL_BIN"
ok "Launcher installed: hardware-compat"

# ── .desktop entry (GNOME/KDE app launcher) ──────────────────────
step "Installing desktop entry (app launcher)..."
mkdir -p "$DESKTOP_DIR"
ICON_PATH="$SCRIPT_DIR/gui/static/icon.svg"

cat > "$DESKTOP_FILE" << DESKTOP
[Desktop Entry]
Version=1.0
Name=Hardware Compat
Comment=Hardware compatibility checker and driver advisor
Exec=bash -c 'hardware-compat --gui'
Icon=${ICON_PATH}
Terminal=false
Type=Application
Categories=System;HardwareSettings;
Keywords=hardware;driver;compatibility;linux;
StartupNotify=true
DESKTOP

# Refresh desktop database
if command -v update-desktop-database &>/dev/null; then
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
fi
ok "Desktop entry: $DESKTOP_FILE"
ok "You can now find 'Hardware Compat' in your app launcher"

# ── Summarise ─────────────────────────────────────────────────────
echo ""
echo -e "  ${G}${B}Installation complete.${NC}"
echo    "  ──────────────────────────────────────────"
echo -e "  ${B}From any terminal:${NC}"
echo    "    hardware-compat            # uses saved default mode"
echo    "    hardware-compat --gui      # force web GUI"
echo    "    hardware-compat --cli      # force CLI report"
echo    "    hardware-compat --cli --report   # report only, no prompts"
echo    "    hardware-compat --cli --json     # raw JSON"
echo ""
echo -e "  ${B}Or open 'Hardware Compat' from your app launcher.${NC}"
echo ""
